//! Sondeo de cobertura (temporal): alimenta un corpus de declaraciones CSS
//! reales y reporta cuáles se dropean (no producen ningún `Decl`).
//! Correr con: cargo test -p puriy-engine --lib style::tests::probe -- --nocapture
use super::super::*;

fn decls(s: &str) -> Vec<Decl> {
    parse_declarations(s, &std::collections::HashMap::new())
}

/// Herramienta de minería de gaps, no un test de regresión: nunca falla,
/// sólo imprime las declaraciones dropeadas. Correr a demanda con:
/// `cargo test -p puriy-engine --lib style::tests::probe -- --ignored --nocapture`.
#[test]
#[ignore]
fn sondeo_drops() {
    let corpus: &[&str] = &[
        // ── color / paint ──
        "color: color-mix(in oklch, red, blue 30%)",
        "color: light-dark(black, white)",
        "color: rgb(from red r g b / 0.5)",
        "background-color: color(display-p3 1 0 0)",
        "caret-color: auto",
        "accent-color: rebeccapurple",
        "color-scheme: light dark",
        "forced-color-adjust: none",
        "print-color-adjust: economy",
        // ── backgrounds / borders ──
        "background: url(x.png) center / cover no-repeat",
        "background-blend-mode: multiply, screen",
        "border-image: url(b.png) 30 fill / 10px / 20px round",
        "border-image-source: linear-gradient(red, blue)",
        "border-image-slice: 30 fill",
        "border-image-width: 10px 20px",
        "border-image-outset: 5px",
        "border-image-repeat: round stretch",
        "box-shadow: inset 0 0 5px 2px red, 1px 1px black",
        // ── text ──
        "text-wrap: balance",
        "text-wrap-style: pretty",
        "text-wrap-mode: nowrap",
        "text-spacing-trim: trim-start",
        "text-autospace: normal",
        "word-break: auto-phrase",
        "line-break: anywhere",
        "hanging-punctuation: first last",
        "text-emphasis: filled circle red",
        "text-emphasis-style: open dot",
        "text-emphasis-color: red",
        "text-emphasis-position: over right",
        "text-indent: 2em hanging each-line",
        "tab-size: 4",
        "text-justify: inter-word",
        "text-decoration: underline wavy red 2px",
        "text-decoration-skip-ink: all",
        "text-underline-offset: auto",
        "initial-letter: 3 2",
        "initial-letter-align: alphabetic",
        // ── fonts ──
        "font: italic bold 16px/1.5 'Times', serif",
        "font-variant: small-caps common-ligatures",
        "font-variant-alternates: stylistic(foo) styleset(bar)",
        "font-variant-numeric: oldstyle-nums tabular-nums",
        "font-variant-east-asian: jis78 full-width",
        "font-variant-ligatures: no-common-ligatures",
        "font-variant-caps: all-small-caps",
        "font-feature-settings: 'liga' 1, 'kern' on",
        "font-variation-settings: 'wght' 700, 'wdth' 80",
        "font-optical-sizing: auto",
        "font-palette: --my-palette",
        "font-kerning: normal",
        "font-stretch: condensed",
        "font-language-override: 'ENG'",
        // ── flexbox / grid ──
        "flex: 1 1 auto",
        "flex-flow: row wrap",
        "place-items: center stretch",
        "place-content: space-between center",
        "place-self: start end",
        "gap: 10px 20px",
        "grid-template: 'a b' 1fr / auto 1fr",
        "grid: auto-flow 1fr / repeat(3, 1fr)",
        "grid-template-columns: repeat(auto-fit, minmax(100px, 1fr))",
        "grid-template-columns: [full-start] minmax(1em, 1fr) [main-start]",
        "grid-row: 1 / span 2",
        "grid-column: span 3",
        "aspect-ratio: 16 / 9",
        "aspect-ratio: auto 4/3",
        // ── transforms / animation ──
        "transform: matrix3d(1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1)",
        "transform: perspective(500px) rotate3d(1,1,1,45deg)",
        "translate: 10px 20px 30px",
        "rotate: x 45deg",
        "scale: 1.5",
        "transition: all 0.3s ease-in-out 0.1s, color 1s",
        "animation: slide 2s ease infinite alternate both",
        "animation-composition: replace add accumulate",
        "transition-property: transform, opacity",
        "offset: path('M0 0') 50% 90deg",
        "will-change: transform, opacity",
        // ── filters / effects ──
        "filter: blur(5px) brightness(1.2) drop-shadow(0 0 5px red)",
        "backdrop-filter: blur(10px)",
        "mix-blend-mode: difference",
        "mask: url(m.svg) luminance",
        "clip-path: polygon(0 0, 100% 0, 50% 100%)",
        "clip-path: circle(50% at center)",
        "clip-path: inset(10px round 5px)",
        "clip-path: path('M0 0L10 10')",
        // ── positioning / sizing ──
        "inset: 10px 20px",
        "inset-block: 5px 10px",
        "width: clamp(200px, 50%, 800px)",
        "width: fit-content(300px)",
        "height: min-content",
        "max-width: max-content",
        "object-fit: scale-down",
        "object-position: right bottom",
        "anchor-name: --foo",
        "position-anchor: --foo",
        "inset-area: top left",
        // ── scroll ──
        "scroll-snap-type: x mandatory",
        "scroll-snap-align: start end",
        "scroll-behavior: smooth",
        "overscroll-behavior: contain auto",
        "scroll-timeline-name: --t",
        "scrollbar-color: red blue",
        "scrollbar-width: thin",
        "scrollbar-gutter: stable both-edges",
        // ── misc / ui ──
        "cursor: url(c.png) 4 4, pointer",
        "appearance: none",
        "user-select: none",
        "pointer-events: bounding-box",
        "touch-action: pan-x pinch-zoom",
        "caret-shape: bar",
        "field-sizing: content",
        "content: 'x' / 'alt text'",
        "content: counter(item, decimal) '. '",
        "content: open-quote close-quote",
        "quotes: '«' '»'",
        "counter-reset: section 0",
        "counter-increment: section 2",
        "counter-set: section 1",
        "list-style: square inside url(d.png)",
        "all: revert-layer",
        "display: inline flow-root",
        "display: flex",
        "visibility: collapse",
        "contain: layout paint size",
        "content-visibility: auto",
        "container: foo / inline-size",
        "view-transition-name: slide",
        "isolation: isolate",
        "image-rendering: pixelated",
        "image-orientation: from-image",
        "mix-blend-mode: plus-lighter",
        "shape-rendering: crispEdges",
        "paint-order: stroke fill markers",
        "d: path('M0 0')",
        "math-style: compact",
        "math-depth: add(2)",
        "math-shift: compact",
        "-webkit-line-clamp: 3",
        "line-clamp: 3",
        "tab-size: 2",
        "white-space-collapse: preserve",
        "ruby-merge: collapse",
        "text-orientation: upright",
        "baseline-shift: super",
        "baseline-source: first",
        "alignment-baseline: central",
        "dominant-baseline: hanging",
        "vector-effect: non-scaling-stroke",
        "color-interpolation: sRGB",
        "stroke-dasharray: 4 2",
        "stroke-dashoffset: 5px",
        "stroke-linecap: round",
        "stroke-linejoin: bevel",
        "stroke-miterlimit: 4",
        "fill-rule: evenodd",
        "clip-rule: nonzero",
        "transform-style: preserve-3d",
        "perspective: 800px",
        "perspective-origin: center",
        "backface-visibility: hidden",
        "rotate: none",
        // ── lote 2: valores raros / specs nuevísimas ──
        "white-space: break-spaces",
        "overflow: clip",
        "overflow-clip-margin: content-box 5px",
        "overflow-block: clip",
        "overflow-inline: scroll",
        "text-box-trim: trim-both",
        "text-box-edge: cap alphabetic",
        "text-box: trim-both cap alphabetic",
        "corner-shape: round bevel",
        "corner-top-left-shape: scoop",
        "reading-flow: grid-order",
        "reading-order: 2",
        "anchor-scope: all",
        "timeline-scope: --t1, --t2",
        "view-transition-class: card",
        "view-transition-group: nearest",
        "overlay: auto",
        "font-size-adjust: ex-height 0.5",
        "font-size-adjust: 0.5",
        "text-spacing: space-first",
        "caret-animation: manual",
        "interest-target-delay: 0.5s",
        "scroll-marker-group: after",
        "scroll-initial-target: nearest",
        "scroll-start: 100px",
        "scroll-start-target: auto",
        "block-ellipsis: auto",
        "continue: discard",
        "max-lines: 3",
        "region-fragment: break",
        "marker-side: match-parent",
        "alignment-baseline: text-before-edge",
        "speak: never",
        "speak-as: spell-out",
        "voice-family: male",
        "nav-up: auto",
        "nav-index: 1",
        "border-spacing: 2px 4px",
        "caption-side: bottom",
        "empty-cells: hide",
        "table-layout: fixed",
        "border-collapse: collapse",
        "widows: 3",
        "orphans: 2",
        "break-before: column",
        "break-inside: avoid-page",
        "box-decoration-break: clone",
        "page: chapter",
        "page-break-after: always",
        "columns: 3 200px",
        "column-rule: 1px solid red",
        "column-fill: balance-all",
        "column-span: all",
        "gap-rule: 1px solid red",
        "row-rule-color: red",
        "rule-width: 2px",
        "text-combine-upright: digits 4",
        "ruby-position: inter-character",
        "writing-mode: sideways-rl",
        "text-orientation: sideways",
        "unicode-bidi: isolate-override",
        "direction: rtl",
        "hyphens: manual",
        "overflow-wrap: anywhere",
        "word-spacing: 0.25em",
        "letter-spacing: 0.1em",
        "text-align: match-parent",
        "text-align-last: justify",
        "text-justify: distribute",
        "vertical-align: -webkit-baseline-middle",
        "zoom: 1.5",
        "zoom: 150%",
        "image-resolution: from-image 300dpi",
        "shape-margin: 1em",
        "shape-outside: margin-box",
        "transform-origin: left top 5px",
        "transform-box: fill-box",
        "transition-timing-function: cubic-bezier(0.1, 0.7, 1, 0.1)",
        "transition-timing-function: steps(4, jump-end)",
        "animation-timing-function: steps(4, jump-none)",
        "animation-iteration-count: 3",
        "animation-fill-mode: forwards",
        "animation-play-state: paused",
        "animation-timeline: scroll(root block)",
        "animation-timeline: view()",
        "animation-range: cover 0% cover 100%",
        "animation-delay: 0.5s",
        "speak-header: always",
        "pause: 20ms",
        "rest-before: 1s",
        "cue-before: url(beep.wav)",
        "mask-border: url(b.png) 25% / 35px 12px repeat",
        "mask-border-mode: alpha",
        "mask-clip: no-clip",
        "background-clip: text",
        "background-clip: border-area",
        "background-origin: content-box",
        "background-attachment: local fixed",
        "background-repeat: round space",
        "background-size: auto 50%",
        "border-block: 2px solid red",
        "border-block-start: 1px dashed",
        "border-inline-color: red blue",
        "outline: 2px dotted red",
        "outline-offset: 4px",
        "resize: block",
        "object-view-box: inset(10%)",
        "aspect-ratio: 1",
        "min-inline-size: max-content",
        "max-block-size: fit-content",
        "inline-size: stretch",
        "contain-intrinsic-size: auto 300px",
        "container-type: scroll-state",
        "color: contrast-color(red)",
        "color: oklch(from blue l c h)",
        "background: paint(myWorklet)",
        "background-image: image-set('a.png' 1x, 'b.png' 2x)",
        "background-image: cross-fade(20% url(a), url(b))",
        "background-image: -webkit-gradient(linear, left top, right top, from(red), to(blue))",
        "background-image: repeating-conic-gradient(red 0deg 10deg, blue 10deg 20deg)",
        "cursor: grab",
        "cursor: -webkit-grab",
        "pointer-events: all",
        "touch-action: manipulation",
        "user-select: contain",
        "scrollbar-gutter: stable",
        "accent-color: auto",
        "caret-color: currentColor",
        "appearance: auto",
        "appearance: textfield",
        "outline-color: invert",
        "text-decoration-thickness: from-font",
        "text-underline-position: from-font",
        "text-decoration-line: spelling-error",
        "text-decoration-style: double",
        "-webkit-text-stroke: 1px red",
        "-webkit-text-fill-color: red",
        "-webkit-box-orient: vertical",
        "-webkit-mask-image: url(m.png)",
        "filter: hue-rotate(90deg) saturate(2) invert(1) sepia(0.5) contrast(2) opacity(0.5) grayscale(1)",
        "filter: url(#myfilter)",
        "transition: display 1s allow-discrete",
        "translate: none",
        "scale: none",
        // ── lote 3: sintaxis correcta + props raras-pero-reales ──
        "animation-composition: add",
        "animation-composition: replace, add, accumulate",
        "corner-top-left-shape: round",
        "corner-bottom-right-shape: bevel",
        "corner-block-start-shape: scoop",
        "scroll-start: 100px",
        "scroll-start-block: center",
        "scroll-start-inline: start",
        "scroll-start-target: auto",
        "scroll-start-target-block: auto",
        "speak: normal",
        "speak-as: spell-out digits",
        "voice-family: female",
        "voice-rate: fast",
        "voice-pitch: high",
        "voice-volume: loud",
        "voice-balance: left",
        "voice-stress: strong",
        "voice-duration: 2s",
        "pause: 20ms 40ms",
        "pause-before: weak",
        "pause-after: strong",
        "rest: 1s 2s",
        "cue: url(a.wav) url(b.wav)",
        "column-rule-style: dashed",
        "marker-side: match-side",
        "gap-rule-color: red",
        "gap-rule-style: solid",
        "gap-rule-width: 2px",
        "row-rule-color: red",
        "column-rule: 2px solid red",
        "text-spacing-trim: space-all",
        "ruby-merge: auto",
        "ruby-overhang: auto",
        "alignment-baseline: hanging",
        "baseline-shift: 50%",
        "baseline-source: last",
        "nav-down: #foo",
        "nav-left: auto",
        "nav-right: #bar",
        "glyph-orientation-horizontal: 90deg",
        "color-adjust: exact",
        "azimuth: center",
        "elevation: above",
        "play-during: url(x.wav) mix",
        "richness: 50",
        "pitch: medium",
        "pitch-range: 50",
        "stress: 50",
        "speech-rate: fast",
        "volume: loud",
        "marks: crop cross",
        "size: a4 landscape",
        "bleed: 6pt",
        "marks: none",
        "transform: translate(10px, 20px) scale(2) rotate(45deg)",
        "transform: translateX(10px) translateY(20px) translateZ(5px)",
        "background: red content-box padding-box",
        "grid-template-columns: subgrid [a] [b]",
        "grid-template-rows: masonry",
        "width: round(up, 17px, 5px)",
        "width: calc(100% - 2 * 10px)",
        "margin: calc(1em + 2px) auto",
        "filter: contrast(0.5) brightness(2)",
        "shape-outside: polygon(0 0, 100% 0, 0 100%)",
        "clip-path: rect(0 100px 100px 0)",
        "clip-path: xywh(0 0 100px 50px round 5px)",
        "clip-path: shape(from 0 0, line to 10px 10px)",
        "offset-path: ray(45deg closest-side)",
        "transition: opacity 1s, transform 2s 0.5s linear",
        "will-change: scroll-position, contents",
        "contain: strict",
        "content: counters(item, '.', decimal)",
        "content: attr(data-x) ' ' attr(data-y)",
        "content: linear-gradient(red, blue)",
        "list-style-type: '→'",
        "quotes: auto",
        "cursor: zoom-in",
        "cursor: ew-resize",
        "vertical-align: 0.5em",
        "line-height: 1.5",
        "white-space: pre-wrap",
        "tab-size: 4px",
        "text-emphasis-style: filled sesame",
        "font-variant-position: sub",
        "font-synthesis: weight style small-caps position",
        "font-display: swap",
        "src: url(font.woff2) format('woff2')",
        "unicode-range: U+0000-00FF",
        "syntax: '<color>'",
        "inherits: true",
        "initial-value: red",
        // ── lote 4: sintaxis de valor moderna ──
        "transition-timing-function: linear(0, 0.5 50%, 1)",
        "animation-timing-function: linear(0, 1)",
        "transition: opacity 1s linear(0, 1)",
        "top: anchor(--foo bottom)",
        "left: anchor(top)",
        "width: anchor-size(--foo width)",
        "height: anchor-size(width)",
        "inset: calc(anchor(top) + 10px)",
        "color: rgb(255 0 0 / 50%)",
        "color: hsl(120 50% 50% / 0.5)",
        "color: oklab(0.5 0.1 0.1)",
        "color: hwb(120 0% 0%)",
        "background: linear-gradient(in oklch, red, blue)",
        "background: linear-gradient(in hsl longer hue, red, blue)",
        "background: conic-gradient(from 45deg at center, red, blue)",
        "background-position: bottom 10px right 20px",
        "grid-row: 2 / -1",
        "grid-column: col-start / span 2",
        "font: menu",
        "font: caption",
        "line-height: calc(1em + 2px)",
        "text-shadow: 1px 1px 2px red, 0 0 1em blue",
        "clip-path: circle(closest-side at 50% 50%)",
        "transform: rotate(0.25turn) skew(10deg, 20deg)",
        "scale: 50%",
        "rotate: 1turn",
        "offset-rotate: auto 90deg",
        "grid-template: repeat(2, [r] 1fr) / repeat(3, [c] 1fr)",
        "aspect-ratio: 2 / 3",
        "text-emphasis-position: under left",
        "border-image: repeating-linear-gradient(red, blue) 30",
        "mask: linear-gradient(black, transparent)",
        "width: calc(min(50%, 300px) + 10px)",
        "margin: 10px max(20px, 5%)",
        "width: round(nearest, 17px, 5px)",
        "width: calc(1px * pi)",
        "background-color: rgb(from red r g b / 0.5)",
        "color: color-mix(in srgb, red 40%, blue)",
        "filter: drop-shadow(2px 2px 0 currentColor)",
        "transition-property: --my-var",
        "scroll-start: 100px",
        "scroll-start-block: center",
        "scroll-start-target: auto",
        "row-rule-color: red",
        "row-rule-style: solid",
        "row-rule-width: 2px",
        "row-rule: 2px solid red",
        "rule-color: red",
        "rule-style: dashed",
        "rule-width: 3px",
        "rule: 1px solid blue",
        "text-spacing: trim-start space-first",
        "white-space-trim: discard-before",
        "wrap-after: avoid",
        "wrap-before: auto",
        "wrap-inside: avoid",
        // ── lote 5: barrido amplio de nombres de propiedad ──
        "all: unset",
        "float: inline-start",
        "clear: both",
        "clear: inline-end",
        "min-width: auto",
        "z-index: 5",
        "order: 2",
        "flex-basis: content",
        "opacity: 0.5",
        "box-sizing: border-box",
        "overflow-x: hidden",
        "overflow-y: auto",
        "text-transform: full-width",
        "text-transform: math-auto",
        "letter-spacing: normal",
        "vertical-align: middle",
        "white-space: pre-line",
        "background-position: 50% 50%",
        "transform-origin: center",
        "transition-delay: 0s",
        "animation-name: none",
        "animation-direction: alternate-reverse",
        "cursor: not-allowed",
        "pointer-events: visiblePainted",
        "clip: rect(0, 0, 0, 0)",
        "clip: auto",
        "color-interpolation-filters: linearRGB",
        "flood-color: currentColor",
        "lighting-color: white",
        "stop-color: red",
        "stop-opacity: 0.5",
        "fill-opacity: 0.3",
        "stroke-width: 2",
        "stroke-opacity: 0.5",
        "marker: url(#m)",
        "mask-type: alpha",
        "isolation: auto",
        "background-repeat: repeat-x",
        "list-style-position: inside",
        "caption-side: top",
        "counter-reset: none",
        "content: normal",
        "content: no-open-quote",
        "outline-style: auto",
        "outline-width: thin",
        "border-collapse: separate",
        "table-layout: auto",
        "direction: ltr",
        "unicode-bidi: plaintext",
        "writing-mode: vertical-lr",
        "text-orientation: mixed",
        "image-rendering: crisp-edges",
        "object-fit: none",
        "mix-blend-mode: color-burn",
        "backdrop-filter: none",
        "will-change: auto",
        "scroll-snap-stop: always",
        "scroll-padding: 10px",
        "scroll-margin: 5px",
        "overscroll-behavior-x: none",
        "touch-action: none",
        "user-select: all",
        "caret-color: transparent",
        "accent-color: currentColor",
        "color-scheme: only light",
        "forced-color-adjust: auto",
        "print-color-adjust: exact",
        "font-kerning: auto",
        "font-size: larger",
        "font-size: smaller",
        "font-weight: bolder",
        "font-weight: 350",
        "font-style: oblique 14deg",
        "font-stretch: 75%",
        "line-height: -moz-block-height",
        "tab-size: 8",
        "hyphens: auto",
        "quotes: none",
        "widows: 2",
        "break-after: avoid-column",
        "page-break-inside: avoid",
        "orphans: 3",
        "columns: auto",
        "column-gap: normal",
        "row-gap: 10px",
        "gap: normal",
        "align-content: space-evenly",
        "justify-items: legacy center",
        "justify-self: safe center",
        "align-items: first baseline",
        "align-self: last baseline",
        "place-content: safe center start",
        "inset-inline: 10px 20px",
        "inset-block-start: 5px",
        "margin-block: 10px",
        "padding-inline: 20px",
        "border-start-start-radius: 5px",
        "min-block-size: 0",
        "max-inline-size: none",
        "block-size: auto",
        "contain: content",
        "content-visibility: hidden",
        "container-name: none",
        "view-transition-name: none",
        "anchor-name: none",
        "position-anchor: auto",
        "field-sizing: fixed",
        "text-emphasis-skip: spaces",
        "ruby-position: over",
        "initial-letter: normal",
        "hanging-punctuation: none",
        "text-combine-upright: all",
        "writing-mode: sideways-lr",
        "math-depth: auto-add",
        "-webkit-appearance: none",
        "-webkit-user-select: none",
        "-webkit-box-shadow: 0 0 5px red",
        "-webkit-transform: scale(2)",
        "-webkit-transition: all 1s",
        "-webkit-border-radius: 5px",
        "-webkit-background-clip: text",
        "-webkit-font-smoothing: antialiased",
        "-moz-osx-font-smoothing: grayscale",
        "-webkit-overflow-scrolling: touch",
        "-webkit-tap-highlight-color: transparent",
        // ── lote 6: barrido de specs nuevas + vendor legacy ──
        "position-area: top left",
        "position-try-order: most-height",
        "position-try-fallbacks: flip-block, flip-inline",
        "position-try: most-width flip-block",
        "position-visibility: anchors-visible",
        "interpolate-size: allow-keywords",
        "font-width: condensed",
        "font-variant-emoji: emoji",
        "transition-behavior: allow-discrete",
        "animation-range-start: cover 0%",
        "animation-range-end: cover 100%",
        "contain-intrinsic-width: 200px",
        "contain-intrinsic-height: auto 300px",
        "contain-intrinsic-block-size: 100px",
        "contain-intrinsic-inline-size: none",
        "margin-trim: block",
        "margin-break: keep",
        "hyphenate-character: '-'",
        "hyphenate-limit-chars: 6 3 2",
        "line-height-step: 18px",
        "block-step-size: 1em",
        "block-step-insert: margin-box",
        "block-step-align: center",
        "block-step-round: up",
        "block-step: 1em margin-box up center",
        "ruby-align: center",
        "text-edge: cap alphabetic",
        "leading-trim: both",
        "input-security: auto",
        "text-rendering: optimizeLegibility",
        "font-smooth: always",
        "-webkit-font-smoothing: subpixel-antialiased",
        "container-type: size",
        "mask-composite: add",
        "mask-mode: luminance",
        "mask-position: center",
        "mask-size: cover",
        "mask-repeat: no-repeat",
        "mask-origin: border-box",
        "offset-distance: 50%",
        "offset-anchor: top right",
        "offset-position: auto",
        "shape-image-threshold: 0.5",
        "margin-trim: inline",
        "-webkit-user-modify: read-write",
        "-webkit-user-drag: element",
        "-webkit-text-security: disc",
        "-webkit-backdrop-filter: blur(5px)",
        "-webkit-box-pack: justify",
        "-webkit-box-align: center",
        "-webkit-box-flex: 1",
        "-webkit-box-ordinal-group: 2",
        "-webkit-box-direction: normal",
        "-webkit-flex-direction: row",
        "-webkit-justify-content: center",
        "-webkit-align-items: stretch",
        "-webkit-flex: 1 1 auto",
        "color-scheme: light dark",
        "scrollbar-gutter: stable both-edges",
        "text-emphasis-position: auto",
        "caret: auto bar",
        "dynamic-range-limit: standard",
        "border-boundary: parent",
        "white-space: wrap",
        // ── lote 7: SVG, scroll-driven, view-transitions, color, grid ──
        "stop-color: color-mix(in srgb, red, blue)",
        "fill: context-fill",
        "stroke: context-stroke",
        "color-interpolation-filters: sRGB",
        "marker-start: url(#m)",
        "marker-mid: none",
        "marker-end: url(#arrow)",
        "shape-inside: circle(50%)",
        "x: 10px",
        "y: 5px",
        "r: 20px",
        "cx: 50%",
        "cy: 50%",
        "rx: 10px",
        "ry: 8px",
        "timeline-scope: --t1, --t2",
        "view-transition-name: auto",
        "view-transition-class: card hero",
        "scroll-snap-stop: normal",
        "overflow-anchor: none",
        "anchor-scope: --a, --b",
        "text-spacing: auto",
        "white-space-collapse: break-spaces",
        "font-feature-settings: normal",
        "font-variation-settings: normal",
        "grid-auto-flow: row dense",
        "grid-auto-columns: minmax(100px, auto)",
        "grid-auto-rows: 1fr",
        "background-position-x: right 10px",
        "background-position-y: bottom",
        "transform-origin: 50% 50% 0",
        "rotate: z 90deg",
        "translate: 0 0",
        "color: hsla(120, 50%, 50%, 0.5)",
        "color: rgba(255, 0, 0, 0.5)",
        "color: lch(50% 40 130 / 0.5)",
        "outline: medium solid",
        "border-image-repeat: space round",
        "scroll-padding-block: 10px 20px",
        "scroll-margin-inline: 5px",
        "inset-inline-start: 10px",
        "contain-intrinsic-size: 100px 200px",
        "text-underline-offset: 2px",
        "text-decoration-skip-box: all",
        "animation-trigger: --t",
        "color-adjust: economy",
        "print-color-adjust: economy",
        "speak-punctuation: code",
        "speak-numeral: digits",
        // ── lote 8: bleeding-edge 2024-2025 + math + color nuevos ──
        "color: device-cmyk(0 1 0 0)",
        "color: contrast-color(blue)",
        "color: rgb(from var(--c) r g b)",
        "width: calc-size(auto, size)",
        "height: calc-size(max-content, size * 2)",
        "width: abs(-10px)",
        "width: sign(-5px) * 10px",
        "rotate: atan2(1, 2)",
        "width: calc(hypot(3px, 4px))",
        "width: calc(10px * pow(2, 3))",
        "width: calc(sqrt(16) * 1px)",
        "width: calc(mod(10px, 3px))",
        "width: calc(rem(10px, 3px))",
        "width: calc(log(100) * 1px)",
        "width: calc(exp(1) * 1px)",
        "transform: rotate(calc(sin(45deg) * 1rad))",
        "transition-timing-function: linear(0 0%, 1 100%)",
        "animation-range: entry 0% exit 100%",
        "scroll-timeline: --t block",
        "view-timeline: --v inline",
        "view-timeline-inset: auto 10px",
        "timeline-scope: none",
        "reading-flow: flex-visual",
        "reading-order: 0",
        "field-sizing: content",
        "text-spacing-trim: trim-all",
        "text-autospace: ideograph-alpha ideograph-numeric",
        "white-space-collapse: preserve-breaks",
        "hyphenate-limit-lines: 2",
        "hyphenate-limit-last: always",
        "tab-size: 4 8",
        "caret-shape: block",
        "scrollbar-width: none",
        "scroll-marker-group: before",
        "anchor-name: --a",
        "position-anchor: --a",
        "position-area: block-start span-inline-start",
        "inset-area: center",
        "font-synthesis-position: auto",
        "font-variant-emoji: text",
        "line-clamp: 3",
        "block-ellipsis: '…'",
        "continue: collapse",
        "scroll-snap-align: none",
        "overflow: clip visible",
        "overflow-clip-margin: 2px",
        "container: layout / size",
        "container-name: card slider",
        "view-transition-class: none",
        "text-wrap: stable",
    ];

    let mut dropped = Vec::new();
    for &c in corpus {
        let prop = c.split(':').next().unwrap().trim();
        let _ = prop;
        let out = decls(c);
        if out.is_empty() {
            dropped.push(c);
        }
    }
    eprintln!("\n=== SONDEO: {} dropeadas de {} ===", dropped.len(), corpus.len());
    for p in &dropped {
        eprintln!("DROP  {}", p);
    }
    eprintln!("=== fin sondeo ===\n");
}

/// Sondeo de cobertura de SELECTORES: alimenta selectores reales y reporta
/// cuáles `parse_selector` dropea (devuelve `None` → la regla entera se
/// pierde). Correr con:
/// `cargo test -p puriy-engine --lib style::tests::probe::sondeo_selectores -- --ignored --nocapture`.
#[test]
#[ignore]
fn sondeo_selectores() {
    let corpus: &[&str] = &[
        // ── pseudo-clases de estado de formulario ──
        "input:valid",
        "input:invalid",
        "input:in-range",
        "input:out-of-range",
        "input:placeholder-shown",
        "input:user-valid",
        "input:user-invalid",
        "input:default",
        "input:indeterminate",
        "input:autofill",
        "input:blank",
        // ── pseudo-clases de interacción/enlace ──
        "a:active",
        "a:visited",
        "a:focus-within",
        "button:focus-visible",
        "div:target",
        "div:target-within",
        "section:scope",
        // ── popover / dialog / media ──
        "[popover]:popover-open",
        "dialog:modal",
        "details:open",
        "details:closed",
        ":fullscreen",
        "video:playing",
        "video:paused",
        "video:muted",
        "video:seeking",
        "video:buffering",
        "video:stalled",
        // ── funcionales nuevas ──
        "div:dir(rtl)",
        "div:dir(ltr)",
        ":nth-child(2 of .item)",
        ":nth-last-child(1 of li)",
        "x-card:state(active)",
        ":host",
        ":host(.theme-dark)",
        ":host-context(.rtl)",
        "::slotted(span)",
        ":is(h1, h2):has(+ p)",
        // ── pseudo-elementos modernos ──
        "input::placeholder",
        "::selection",
        "li::marker",
        "p::first-line",
        "p::first-letter",
        "dialog::backdrop",
        "input::file-selector-button",
        "details::details-content",
        "::target-text",
        "::spelling-error",
        "::grammar-error",
        "::highlight(foo)",
        "x-el::part(label)",
        "::view-transition-group(root)",
        // ── nesting (CSS Nesting) ──
        "&:hover",
        "& > .child",
        // ── combos que ya deberían andar (control) ──
        "ul > li:first-child",
        "a[href^='https']:hover",
        ".a .b .c",
    ];

    let mut dropped = Vec::new();
    for &c in corpus {
        if parse_selector(c).is_none() {
            dropped.push(c);
        }
    }
    eprintln!("\n=== SONDEO SELECTORES: {} dropeados de {} ===", dropped.len(), corpus.len());
    for p in &dropped {
        eprintln!("DROP  {}", p);
    }
    eprintln!("=== fin sondeo selectores ===\n");
}
