//! Sondeo de cobertura (temporal): alimenta un corpus de declaraciones CSS
//! reales y reporta cuáles se dropean (no producen ningún `Decl`).
//! Correr con: cargo test -p puriy-engine --lib style::tests::probe -- --nocapture
use super::super::*;

fn decls(s: &str) -> Vec<Decl> {
    parse_declarations(s, &std::collections::HashMap::new())
}

/// Herramienta de minería de gaps, no un test de regresión: nunca falla,
/// sólo imprime las declaraciones dropeadas. Correr a demanda con:
/// `cargo test -p puriy-engine --lib style::tests::probe -- --ignored --nocapture`.
#[test]
#[ignore]
fn sondeo_drops() {
    let corpus: &[&str] = &[
        // ── color / paint ──
        "color: color-mix(in oklch, red, blue 30%)",
        "color: light-dark(black, white)",
        "color: rgb(from red r g b / 0.5)",
        "background-color: color(display-p3 1 0 0)",
        "caret-color: auto",
        "accent-color: rebeccapurple",
        "color-scheme: light dark",
        "forced-color-adjust: none",
        "print-color-adjust: economy",
        // ── backgrounds / borders ──
        "background: url(x.png) center / cover no-repeat",
        "background-blend-mode: multiply, screen",
        "border-image: url(b.png) 30 fill / 10px / 20px round",
        "border-image-source: linear-gradient(red, blue)",
        "border-image-slice: 30 fill",
        "border-image-width: 10px 20px",
        "border-image-outset: 5px",
        "border-image-repeat: round stretch",
        "box-shadow: inset 0 0 5px 2px red, 1px 1px black",
        // ── text ──
        "text-wrap: balance",
        "text-wrap-style: pretty",
        "text-wrap-mode: nowrap",
        "text-spacing-trim: trim-start",
        "text-autospace: normal",
        "word-break: auto-phrase",
        "line-break: anywhere",
        "hanging-punctuation: first last",
        "text-emphasis: filled circle red",
        "text-emphasis-style: open dot",
        "text-emphasis-color: red",
        "text-emphasis-position: over right",
        "text-indent: 2em hanging each-line",
        "tab-size: 4",
        "text-justify: inter-word",
        "text-decoration: underline wavy red 2px",
        "text-decoration-skip-ink: all",
        "text-underline-offset: auto",
        "initial-letter: 3 2",
        "initial-letter-align: alphabetic",
        // ── fonts ──
        "font: italic bold 16px/1.5 'Times', serif",
        "font-variant: small-caps common-ligatures",
        "font-variant-alternates: stylistic(foo) styleset(bar)",
        "font-variant-numeric: oldstyle-nums tabular-nums",
        "font-variant-east-asian: jis78 full-width",
        "font-variant-ligatures: no-common-ligatures",
        "font-variant-caps: all-small-caps",
        "font-feature-settings: 'liga' 1, 'kern' on",
        "font-variation-settings: 'wght' 700, 'wdth' 80",
        "font-optical-sizing: auto",
        "font-palette: --my-palette",
        "font-kerning: normal",
        "font-stretch: condensed",
        "font-language-override: 'ENG'",
        // ── flexbox / grid ──
        "flex: 1 1 auto",
        "flex-flow: row wrap",
        "place-items: center stretch",
        "place-content: space-between center",
        "place-self: start end",
        "gap: 10px 20px",
        "grid-template: 'a b' 1fr / auto 1fr",
        "grid: auto-flow 1fr / repeat(3, 1fr)",
        "grid-template-columns: repeat(auto-fit, minmax(100px, 1fr))",
        "grid-template-columns: [full-start] minmax(1em, 1fr) [main-start]",
        "grid-row: 1 / span 2",
        "grid-column: span 3",
        "aspect-ratio: 16 / 9",
        "aspect-ratio: auto 4/3",
        // ── transforms / animation ──
        "transform: matrix3d(1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1)",
        "transform: perspective(500px) rotate3d(1,1,1,45deg)",
        "translate: 10px 20px 30px",
        "rotate: x 45deg",
        "scale: 1.5",
        "transition: all 0.3s ease-in-out 0.1s, color 1s",
        "animation: slide 2s ease infinite alternate both",
        "animation-composition: replace add accumulate",
        "transition-property: transform, opacity",
        "offset: path('M0 0') 50% 90deg",
        "will-change: transform, opacity",
        // ── filters / effects ──
        "filter: blur(5px) brightness(1.2) drop-shadow(0 0 5px red)",
        "backdrop-filter: blur(10px)",
        "mix-blend-mode: difference",
        "mask: url(m.svg) luminance",
        "clip-path: polygon(0 0, 100% 0, 50% 100%)",
        "clip-path: circle(50% at center)",
        "clip-path: inset(10px round 5px)",
        "clip-path: path('M0 0L10 10')",
        // ── positioning / sizing ──
        "inset: 10px 20px",
        "inset-block: 5px 10px",
        "width: clamp(200px, 50%, 800px)",
        "width: fit-content(300px)",
        "height: min-content",
        "max-width: max-content",
        "object-fit: scale-down",
        "object-position: right bottom",
        "anchor-name: --foo",
        "position-anchor: --foo",
        "inset-area: top left",
        // ── scroll ──
        "scroll-snap-type: x mandatory",
        "scroll-snap-align: start end",
        "scroll-behavior: smooth",
        "overscroll-behavior: contain auto",
        "scroll-timeline-name: --t",
        "scrollbar-color: red blue",
        "scrollbar-width: thin",
        "scrollbar-gutter: stable both-edges",
        // ── misc / ui ──
        "cursor: url(c.png) 4 4, pointer",
        "appearance: none",
        "user-select: none",
        "pointer-events: bounding-box",
        "touch-action: pan-x pinch-zoom",
        "caret-shape: bar",
        "field-sizing: content",
        "content: 'x' / 'alt text'",
        "content: counter(item, decimal) '. '",
        "content: open-quote close-quote",
        "quotes: '«' '»'",
        "counter-reset: section 0",
        "counter-increment: section 2",
        "counter-set: section 1",
        "list-style: square inside url(d.png)",
        "all: revert-layer",
        "display: inline flow-root",
        "display: flex",
        "visibility: collapse",
        "contain: layout paint size",
        "content-visibility: auto",
        "container: foo / inline-size",
        "view-transition-name: slide",
        "isolation: isolate",
        "image-rendering: pixelated",
        "image-orientation: from-image",
        "mix-blend-mode: plus-lighter",
        "shape-rendering: crispEdges",
        "paint-order: stroke fill markers",
        "d: path('M0 0')",
        "math-style: compact",
        "math-depth: add(2)",
        "math-shift: compact",
        "-webkit-line-clamp: 3",
        "line-clamp: 3",
        "tab-size: 2",
        "white-space-collapse: preserve",
        "ruby-merge: collapse",
        "text-orientation: upright",
        "baseline-shift: super",
        "baseline-source: first",
        "alignment-baseline: central",
        "dominant-baseline: hanging",
        "vector-effect: non-scaling-stroke",
        "color-interpolation: sRGB",
        "stroke-dasharray: 4 2",
        "stroke-dashoffset: 5px",
        "stroke-linecap: round",
        "stroke-linejoin: bevel",
        "stroke-miterlimit: 4",
        "fill-rule: evenodd",
        "clip-rule: nonzero",
        "transform-style: preserve-3d",
        "perspective: 800px",
        "perspective-origin: center",
        "backface-visibility: hidden",
        "rotate: none",
        // ── lote 2: valores raros / specs nuevísimas ──
        "white-space: break-spaces",
        "overflow: clip",
        "overflow-clip-margin: content-box 5px",
        "overflow-block: clip",
        "overflow-inline: scroll",
        "text-box-trim: trim-both",
        "text-box-edge: cap alphabetic",
        "text-box: trim-both cap alphabetic",
        "corner-shape: round bevel",
        "corner-top-left-shape: scoop",
        "reading-flow: grid-order",
        "reading-order: 2",
        "anchor-scope: all",
        "timeline-scope: --t1, --t2",
        "view-transition-class: card",
        "view-transition-group: nearest",
        "overlay: auto",
        "font-size-adjust: ex-height 0.5",
        "font-size-adjust: 0.5",
        "text-spacing: space-first",
        "caret-animation: manual",
        "interest-target-delay: 0.5s",
        "scroll-marker-group: after",
        "scroll-initial-target: nearest",
        "scroll-start: 100px",
        "scroll-start-target: auto",
        "block-ellipsis: auto",
        "continue: discard",
        "max-lines: 3",
        "region-fragment: break",
        "marker-side: match-parent",
        "alignment-baseline: text-before-edge",
        "speak: never",
        "speak-as: spell-out",
        "voice-family: male",
        "nav-up: auto",
        "nav-index: 1",
        "border-spacing: 2px 4px",
        "caption-side: bottom",
        "empty-cells: hide",
        "table-layout: fixed",
        "border-collapse: collapse",
        "widows: 3",
        "orphans: 2",
        "break-before: column",
        "break-inside: avoid-page",
        "box-decoration-break: clone",
        "page: chapter",
        "page-break-after: always",
        "columns: 3 200px",
        "column-rule: 1px solid red",
        "column-fill: balance-all",
        "column-span: all",
        "gap-rule: 1px solid red",
        "row-rule-color: red",
        "rule-width: 2px",
        "text-combine-upright: digits 4",
        "ruby-position: inter-character",
        "writing-mode: sideways-rl",
        "text-orientation: sideways",
        "unicode-bidi: isolate-override",
        "direction: rtl",
        "hyphens: manual",
        "overflow-wrap: anywhere",
        "word-spacing: 0.25em",
        "letter-spacing: 0.1em",
        "text-align: match-parent",
        "text-align-last: justify",
        "text-justify: distribute",
        "vertical-align: -webkit-baseline-middle",
        "zoom: 1.5",
        "zoom: 150%",
        "image-resolution: from-image 300dpi",
        "shape-margin: 1em",
        "shape-outside: margin-box",
        "transform-origin: left top 5px",
        "transform-box: fill-box",
        "transition-timing-function: cubic-bezier(0.1, 0.7, 1, 0.1)",
        "transition-timing-function: steps(4, jump-end)",
        "animation-timing-function: steps(4, jump-none)",
        "animation-iteration-count: 3",
        "animation-fill-mode: forwards",
        "animation-play-state: paused",
        "animation-timeline: scroll(root block)",
        "animation-timeline: view()",
        "animation-range: cover 0% cover 100%",
        "animation-delay: 0.5s",
        "speak-header: always",
        "pause: 20ms",
        "rest-before: 1s",
        "cue-before: url(beep.wav)",
        "mask-border: url(b.png) 25% / 35px 12px repeat",
        "mask-border-mode: alpha",
        "mask-clip: no-clip",
        "background-clip: text",
        "background-clip: border-area",
        "background-origin: content-box",
        "background-attachment: local fixed",
        "background-repeat: round space",
        "background-size: auto 50%",
        "border-block: 2px solid red",
        "border-block-start: 1px dashed",
        "border-inline-color: red blue",
        "outline: 2px dotted red",
        "outline-offset: 4px",
        "resize: block",
        "object-view-box: inset(10%)",
        "aspect-ratio: 1",
        "min-inline-size: max-content",
        "max-block-size: fit-content",
        "inline-size: stretch",
        "contain-intrinsic-size: auto 300px",
        "container-type: scroll-state",
        "color: contrast-color(red)",
        "color: oklch(from blue l c h)",
        "background: paint(myWorklet)",
        "background-image: image-set('a.png' 1x, 'b.png' 2x)",
        "background-image: cross-fade(20% url(a), url(b))",
        "background-image: -webkit-gradient(linear, left top, right top, from(red), to(blue))",
        "background-image: repeating-conic-gradient(red 0deg 10deg, blue 10deg 20deg)",
        "cursor: grab",
        "cursor: -webkit-grab",
        "pointer-events: all",
        "touch-action: manipulation",
        "user-select: contain",
        "scrollbar-gutter: stable",
        "accent-color: auto",
        "caret-color: currentColor",
        "appearance: auto",
        "appearance: textfield",
        "outline-color: invert",
        "text-decoration-thickness: from-font",
        "text-underline-position: from-font",
        "text-decoration-line: spelling-error",
        "text-decoration-style: double",
        "-webkit-text-stroke: 1px red",
        "-webkit-text-fill-color: red",
        "-webkit-box-orient: vertical",
        "-webkit-mask-image: url(m.png)",
        "filter: hue-rotate(90deg) saturate(2) invert(1) sepia(0.5) contrast(2) opacity(0.5) grayscale(1)",
        "filter: url(#myfilter)",
        "transition: display 1s allow-discrete",
        "translate: none",
        "scale: none",
    ];

    let mut dropped = Vec::new();
    for &c in corpus {
        let prop = c.split(':').next().unwrap().trim();
        let _ = prop;
        let out = decls(c);
        if out.is_empty() {
            dropped.push(c);
        }
    }
    eprintln!("\n=== SONDEO: {} dropeadas de {} ===", dropped.len(), corpus.len());
    for p in &dropped {
        eprintln!("DROP  {}", p);
    }
    eprintln!("=== fin sondeo ===\n");
}
